{

    'name': 'job_order_process',
    'version': '1.0',
    'author': 'ERP Softtech Solution',
    'depends': ['base', 'mail', 'mymastertest', 'custom_invoice','dynamic_excel_export','odoo_tree_advance_search','report_creator','rowno_in_tree','hide_any_menu' ],
    'category': ' ',

    'description': '',
    'data': [

        'security/for_security.xml',
        'security/ir.model.access.csv',
        'data/data.xml',
        'views/job_order_challan_receive_view.xml',
        'wizard/issue_material.xml',
        'reports/job_order_issue.xml',
        'reports/challan_bill_report.xml',
        'views/challan_bill_template.xml',
        'views/challan_bill_view.xml',
        'views/challan_status_report_template.xml',
        'views/job_order_challan_view.xml',
        'views/job_order_view.xml',
        'views/sequence_view.xml',
        'views/job_order_issue_template.xml',
        'views/stock_register_view.xml',
        'views/order_inspection.xml',
        'views/order_production.xml',
        'reports/stock_register_report.xml',
        'views/stock_register_template.xml',
        # 'views/res_user_inherit.xml',
        'wizard/move_production_qty.xml',
        'views/job_card.xml',
        'wizard/update_challan.xml',
        'wizard/move_hold_qty.xml',
        'wizard/challan_receipt_line_wizard.xml',
        'views/final_inspection.xml',
        'views/reconcilation.xml',
        'views/joborder_challan_receipt_line.xml',
        'views/res_company_inherit.xml',
        'views/dispatch_advice.xml',
        'views/dispatch_advice_report.xml',
        'views/jobcard.xml',

    ],
    'website': 'www.erpsofttech.com',
    'demo_xml': [],
    'js': [],
    'css': [],

    'installable': True,
    'auto-installable': False,
    'active': False,
}
